### ISSUE TITLE
Tag a place and remind me near that place

### ISSUE THREAD

**Issue by aliiizzz** [FarshidRoohi/ReminderPro#3]
The user can tag a location that will eventually be there and set an approximate time to remind.
when the user is near the location app reminds him of some sort of notification or alarm.
this is useful when people use Buses or metro and fall sleep during travel.

**Comment by aliiizzz** [comment]
I can work on it if it fits with the app

**Comment by FarshidRoohi** [comment]
This option is now available in the app
But it is primitive
And this could be done better
I'm happy to get your idea done.
